# Generated by Django 4.2 on 2023-04-12 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='carga_horario',
            new_name='carga_horaria',
        ),
    ]
